"""empty message

Revision ID: 06374f0f6121
Revises: 
Create Date: 2022-06-05 22:23:47.318775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06374f0f6121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyzes', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'analyzes', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analyzes', type_='foreignkey')
    op.drop_column('analyzes', 'userId')
    # ### end Alembic commands ###
