"""empty message

Revision ID: fcf28ac24e07
Revises: 06374f0f6121
Create Date: 2022-06-05 22:31:49.663363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf28ac24e07'
down_revision = '06374f0f6121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyzes', sa.Column('createdTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyzes', 'createdTime')
    # ### end Alembic commands ###
